version: '3.7'

services:

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:${APP_PATH_CONTAINER}
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    working_dir: ${APP_PATH_CONTAINER}
    depends_on:
      - php

  php:
    build: ./docker/php
    volumes:
      - ./:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${OC_DB_PASSWORD}
      MYSQL_DATABASE: ${OC_DB_DATABASE}
    ports:
      - "33060:3306"
    volumes:
      - ${DB_PATH}:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8765:80
    environment:
      - MYSQL_ROOT_PASSWORD=${OC_DB_PASSWORD}
      - PMA_ARBITRARY=1
      - PMA_HOST=${OC_DB_HOSTNAME}
      - UPLOAD_LIMIT=200M
    depends_on:
      - mysql
